### ISSUE TITLE
Unable to set frequency

### ISSUE THREAD

**Issue by DhruvSangal** [darksidelemm/pi_sstv_shield#1]
I am trying to set frequency using the script, i am using dorji818U model trying to set at 436.000 mhz but sometimes even after getting response as 0 while transmitting image via sstv unable to recieve anything i highly doubt frequency is not getting set can you please help me. Thanks

**Comment by darksidelemm** [comment]
Sorry, I can't really provide support for this repository or the Dorji modules, they do seem to be a bit unreliable when setting frequency.
